### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by ronfuller** [aschmelyun/fleet#3]
This project looks like it would solve some problems with multiple sail apps, but my biggest problem is support SSL throughout on local projects. Right now I run Nginx Proxy Manager with a significant amount of configuration. Are you looking at supporting SSL in this package?

**Comment by lalcebo** [comment]
@ronfuller I do it differently, you can look here `https://github.com/lalcebo/docker-traefik-https`, you might be interested. The `template.yml` file is the one you use in your Laravel project. With this configuration, I can have SSL with different domains, plus I use `dnsmasq` to avoid having to modify the `/etc/hosts` file.

**Comment by tonysm** [comment]
I got something working over here. I'm using [mkcert](https://github.com/FiloSottile/mkcert) to issue the certificate and make my system trust it.

```bash
mkcert -install
mkcert "*.docker.localhost"

mkdir -p $HOME/.traefik/configuration/tls
# rename the files to $HOME/.traefik/configuration/tls/cert.cert and $HOME/.traefik/configuration/tls/cert.key

cat << EOF > $HOME/.traefik/configuration/certificates.yaml
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /configuration/tls/cert.cert
        keyFile: /configuration/tls/cert.key
  certificates:
    - certFile: /configuration/tls/cert.cert
      keyFile: /configuration/tls/cert.key
EOF
```

Then, I ran my traefik container like this:

```bash
docker network create sail-edge

docker run --rm -d --name sail-ingress \
    -p 80:80 -p 443:443 -p 8080:8080 \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v $HOME/.traefik/configuration:/configuration \
    --network=sail-edge \
    traefik:v2.5 \
    --api.insecure=true \
    --providers.docker \
    --entrypoints.web.address=:80 \
    --entrypoints.web-secure.address=:443 \
    --providers.file.directory=/configuration/ \
    --providers.file.watch=true
```

Then, in apps using Laravel Sail I have something like this in my `docker-compose.yml` (this one was called "another-app"):

```yml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        labels:
            - "traefik.enable=true"
            # HTTP with Redirect
            - "traefik.http.middlewares.another-app-redirect-middleware.redirectscheme.scheme=https"
            - "traefik.http.routers.another-app.entrypoints=web"
            - "traefik.http.routers.another-app.rule=Host(`another-app.docker.localhost`)"
            - "traefik.http.routers.another-app.middlewares=another-app-redirect-middleware"
            # HTTPS
            - "traefik.http.routers.another-app-secure.entrypoints=web-secure"
            - "traefik.http.routers.another-app-secure.tls=true"
            - "traefik.http.routers.another-app-secure.rule=Host(`another-app.docker.localhost`)"
            - "traefik.port=80"
        networks:
            - sail-edge
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    sail-edge:
        external: true
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
```

This was tested on both macOS and Linux. By using domains following the `*.docker.localhost` pattern, I avoid having to deal with changing my `/etc/hosts` or dnsmasq.
